version: 2

source:
    - name: pizza_place_sales
      database: PIZZAPLACE
      schema: RAW
      tables:
        - name: ORDERS
          description: Pizza Place Order table
          
          
        - name: ORDER_DETAILS
          description: Pizza Place order detail table.

        - name: PIZZAS
          description: Pizza Place Pizzas with their price, size and type.
        