version: 2

seeds:
  - name: pizza_types
    description: Pizza names and its ingredients.
    columns:
      - name: pizza_type_id
        description: Unique Identifier of the Pizza.
        tests:
          - dbt_expectations.expect_column_values_to_be_unique
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: varchar
          
      - name: name
        description: Name of the Pizza.
        tests:
          - dbt_expectations.expect_column_values_to_be_unique
      - name: category
        description: Category of the Pizza based on the ingredients.
        tests:
          - dbt_expectations.expect_column_values_to_be_in_set:
              value_set: ['Chicken','Veggie','Classic','Supreme']
              quote_values: true
      - name: ingredients
        description: Ingredients used to make the pizza.