version: 2

models:
  - name: stg_orders
    description: A cleaned table derived from the orders source table.
    columns:
      - name: order_id
        description: Id of the order. Primary column for table stg_orders.
        tests:
          - not_null
          - unique



  - name: stg_order_details
    description: A cleaned order details table with price of each order and order type.
    columns:
      - name: sales_id
        description: order details id
        tests:
          - not_null
          - unique
      
      - name: order_id
        description: order id
        tests:
          - not_null

      - name: pizza_type
        description: Type of pizza. It is a field from the seeds data.
        tests:
          - not_null
          - relationships:
              to: ref('pizza_types.sql')
              field: pizza_type_id


      - name: order_quantity
        description: Quantity of order of particular pizza type.
        tests:
          - not_null
      
      - name: pizza_size
        description: size of the pizza
        tests:
          - not_null
          - accepted_values:
              values: ['M','L', 'S', 'XL', 'XXL']

      - name: order_amount
        description: amount paied for the pizza.
        tests:
          - not_null
        

  - name: fct_orders
    description: A order summary table prepared by joining orders and orderdetails
      to show the total quantity and amount of the order.
    columns:
      - name: ORDER_ID
        description: "Order id"
      - name: ORDER_DATETIME
        description: "date time stamp of order"
      - name: TOTAL_ORDER_QUANTITY
        description: "Sum of number of pizzas ordered."
      - name: TOTAL_ORDER_AMOUNT
        description: "Sum of amount of pizzas ordered."
