version: 2

sources:
    - name: pizza_place
      schema: raw
      tables:
        - name: orders
          description: Pizza Place Order table

        - name: order_details
          description: Pizza Place order detail table.

        - name: pizzas
          description: Pizza Place Pizzas with their price, size and type.

